In [1]:
class Person:
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def display(self):
        print(f'{self.name} is {self.age} year old')
        
p1 = Person('John', 20)
p2 = Person('Jack', 34)

p1.display()
p2.display()

John is 20 year old
Jack is 34 year old


In [2]:
class Person:
    
    species = 'Homo Sapiens'
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def display(self):
        print(f'{self.name} is {self.age} year old')
        
p1 = Person('John', 20)
p2 = Person('Jack', 34)

p1.display()
p2.display()

John is 20 year old
Jack is 34 year old


In [3]:
Person.species

'Homo Sapiens'

In [4]:
p1.species

'Homo Sapiens'

In [5]:
p2.species

'Homo Sapiens'

In [6]:
Person.name

AttributeError: type object 'Person' has no attribute 'name'

In [7]:
id(Person.species)

2704506098800

In [8]:
id(p1.species)

2704506098800

In [10]:
id(p2.species)

2704506098800

In [12]:
class Person:
    
    species = 'Homo Sapiens'
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        
    def display(self):
        print(f'{self.name} is {self.age} year old {Person.species}')
        
p1 = Person('John', 20)
p2 = Person('Jack', 34)

p1.display()
p2.display()

John is 20 year old Homo Sapiens
Jack is 34 year old Homo Sapiens


In [13]:
class Person:
    
    species = 'Homo Sapiens'
    count = 0
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        Person.count += 1
        
    def display(self):
        print(f'{self.name} is {self.age} year old {Person.species}')
        
p1 = Person('John', 20)
p2 = Person('Jack', 34)

p1.display()
p2.display()

John is 20 year old Homo Sapiens
Jack is 34 year old Homo Sapiens


In [14]:
Person.count

2

In [15]:
p3 = Person('Jill', 40)

In [16]:
p4 = Person('dig', 44)

In [17]:
Person.count

4

In [20]:
class BankAccount:
    
    rate_of_interest = 5
    minimum_balance = 100
    minimum_balance_fees = 10
    
    def __init__(self, account_number, owner_name, balance):
        self.account_number = account_number
        self.owner_name = owner_name
        self.balance = balance
        
    def withdraw(self, amount):
        self.balance -= amount
        
    def deposit(self, amount):
        self.amount += amount
        
account1 = BankAccount('7348', 'Tom', 50)
account2 = BankAccount('6378', 'Bob', 400)


In [24]:
class Book():
    
    x = 5
    
    def __init__(self):
        self.x = 100
        
    def display(self):
        print(self.x)
        print(Book.x)
        
b = Book()
b.display()


100
5


In [22]:
Book.x

5

In [23]:
b.x

100

In [25]:
class Account():
    
    rate = 5
    
a1 = Account()
a2 = Account()

In [26]:
Account.rate

5

In [27]:
a1.rate

5

In [28]:
a2.rate

5

In [29]:
Account.rate = 6

In [30]:
Account.rate

6

In [31]:
a1.rate

6

In [33]:
a2.rate

6

In [34]:
a1.rate = 7

In [35]:
a1.rate

7

In [36]:
Account.rate

6

In [37]:
a2.rate

6

In [38]:
a1.rate

7

In [39]:
id(Account.rate)

140728048428992

In [40]:
id(a1.rate)

140728048429024

In [41]:
id(a2.rate)

140728048428992

In [42]:
class Account():
    
    rate = 5
    
    def some_method(self):
        print(self.rate, Account.rate, id(self.rate), id(Account.rate))
        self.rate = 10
        print(self.rate, Account.rate, id(self.rate), id(Account.rate))
    
a1 = Account()
a2 = Account()

a1.some_method()

5 5 140728048428960 140728048428960
10 5 140728048429120 140728048428960


In [43]:
class Account():
    
    rate = 5
    
    def some_method(self):
        print(self.rate, Account.rate, id(self.rate), id(Account.rate))
        Account.rate = 10
        print(self.rate, Account.rate, id(self.rate), id(Account.rate))
    
a1 = Account()
a2 = Account()

a1.some_method()

5 5 140728048428960 140728048428960
10 10 140728048429120 140728048429120


In [50]:
class MyClass():
    
    a = 5
    
    def __init__(self, x):
        self._x = x
        
    def method1(self):
        print(self.x)
        
    @classmethod
    def method2(cls):
        print(cls.a)
        
MyClass.method2()


5


NameError: name '__MyClass_method1' is not defined

In [56]:
class Person:
    
    species = 'Homo Sapiens'
    count = 0
    
    def __init__(self, name, age):
        self.name = name
        self.age = age
        Person.count += 1
        
    def display(self):
        print(f'{self.name} is {self.age} year old {Person.species}')
        
    @classmethod
    def show_count(cls):
        print(f'There are {cls.count} {cls.species}')
        
Person.show_count()
        
p1 = Person('John', 20)
p2 = Person('Jack', 34)

p1.show_count()

There are 0 Homo Sapiens
There are 2 Homo Sapiens


In [63]:
class Person:
        
    def __init__(self, name, age):
        self.name = name
        self.age = age
                
    def display(self):
        print('I am', self.name, self.age, 'years old')

    @classmethod
    def from_str(cls, s):
        name,age = s.split(',')
        return cls(name, int(age))
    
    @classmethod
    def from_dict(cls, s):
        return cls( d['name'], d['age'])
    
p1 = Person('John',20)
p2 = Person('Jack',34)

s = 'Jim, 23'
p3 = Person.from_str(s)
p3.display()
d = {'name' : 'Jane', 'age' : 34}
p4 = Person.from_dict(d)
p4.display()

I am Jim 23 years old
I am Jane 34 years old


In [58]:
Person.s

AttributeError: type object 'Person' has no attribute 's'

In [78]:
class Employee:
    def __init__(self,first_name,last_name,birth_year,salary):
        self.first_name = first_name
        self.last_name = last_name
        self.birth_year = birth_year
        self.salary = salary
        
    def show(self):
        print(f'''I am {self.first_name} {self.last_name} born in {self.birth_year} ''')
        

In [85]:

#from employee import Employee
from datetime import datetime
class Person:
        
    def __init__(self,name,age):
        self.name = name
        self.age = age
                
    def display(self):
        print('I am', self.name, self.age, 'years old')

    @classmethod
    def from_str(cls, s):
        name,age = s.split(',')
        return cls(name, int(age))
    
    @classmethod
    def from_dict(cls, d):
        return cls( d['name'], d['age'])
    
    @classmethod
    def from_employee(cls, emp):
        name = emp.first_name + ' ' + emp.last_name
        age = datetime.today().year - emp.birth_year
        return cls(name, age)
    
p1 = Person('John',20)
p2 = Person('Jack',34)

s = 'Jim, 23'
p3 = Person.from_str(s)
p3.display()
d = {'name' : 'Jane', 'age' : 34}
p4 = Person.from_dict(d)
p4.display()

e1 = Employee('james', 'Smith', 2021, 6000)
p5 = Person.from_employee(e1)
p5.display()

I am Jim 23 years old
I am Jane 34 years old
I am james Smith 1 years old


In [6]:
class Course:
    def __init__(self, title, instructor, lectures, price):
        self.title = title
        self.instructor = instructor
        self.price = price
        self.lectures = lectures
        self.users = []
        self.ratings = 0
        self.avg_rating = 0
        
    def __str__(self):
        return f'{self.title} by {self.instructor}'
    
    def new_user_enrolled(self, user):
        self.users.append(user)
        
    def received_a_rating(self, new_rating):
        self.avg_rating = (self.avg_rating * self.ratings + new_rating)/(self.ratings +1)
        self.ratings += 1
        
    def show_details(self):
        print('Course Title : ', self.title)
        print('Instructor : ', self.instructor)
        print('Price : ', self.price)
        print('Number of Lectures : ', self.lectures)
        print('Users : ', self.users)
        print('Average Rating : ', self.avg_rating)
        
class VideoCourse(Course):
    def __init__(self, title, instructor, lectures, price, length_video):
        super().__init__(title, instructor, lectures, price)
        self.length_video = length_video
        
    def show_details(self):
        super().show_details()
        print('Video Length : ', self.length_video)
        
class PdfCourse(Course):
    def __init__(self, title, instructor, lectures, price, pages):
        super().__init__(title, instructor, lectures, price)
        self.pages = pages
        
    def show_details(self):
        super().show_details()
        print('Number of Pages : ', self.pages)
        
vc = VideoCourse('Learn C++', 'Jack', 30, 50, 10)
vc.new_user_enrolled('Allen')
vc.new_user_enrolled('Max')
vc.new_user_enrolled('Tom')
vc.received_a_rating(3)
vc.received_a_rating(5)
vc.received_a_rating(4)
vc.show_details()

print()
 
pc = PdfCourse('Learn Java', 'Jim', 35, 50, 1000)
pc.new_user_enrolled('Allen')
pc.new_user_enrolled('Mary')
pc.new_user_enrolled('JIm')
pc.received_a_rating(5)
pc.received_a_rating(4)
pc.received_a_rating(4.5)
pc.show_details()
        
        

Course Title :  Learn C++
Instructor :  Jack
Price :  50
Number of Lectures :  30
Users :  ['Allen', 'Max', 'Tom']
Average Rating :  4.0
Video Length :  10

Course Title :  Learn Java
Instructor :  Jim
Price :  50
Number of Lectures :  35
Users :  ['Allen', 'Mary', 'JIm']
Average Rating :  4.5
Number of Pages :  1000


In [7]:
class Mother:
        def cook(self):
           print('Can cook pasta')
 
class Father:
        def cook(self):
             print('Can cook noodles')
 
class Daughter(Father, Mother):
          pass
 
class Son(Mother, Father):
         def cook(self):
             super().cook()
             print('Can cook butter chicken') 
 
d = Daughter()  
s = Son()

d.cook()
print()
s.cook()


Can cook noodles

Can cook pasta
Can cook butter chicken


In [8]:
class Person:
    def __init__(self,id):
        self.id = id
        
class Teacher(Person):
    def __init__(self,id):
        Person.__init__(self,id)
        self.id += 'T'
    
class Student(Person):
    def __init__(self,id):
        Person.__init__(self,id)
        self.id += 'S'
   
class TeachingAssistant(Student, Teacher):
     def __init__(self,id):
        Student.__init__(self,id)
        Teacher.__init__(self,id)
       
x = TeachingAssistant('2675')
print(x.id)
y = Student('4567')
print(y.id)
z = Teacher('3421')
print(z.id)
p = Person('5749')
print(p.id)


2675T
4567S
3421T
5749


In [9]:
class Person:
    def __init__(self,id):
        self.id = id
        
class Teacher(Person):
    def __init__(self,id):
        super().__init__(id)
        self.id += 'T'
    
class Student(Person):
    def __init__(self,id):
        super().__init__(id)
        self.id += 'S'
   
class TeachingAssistant(Student, Teacher):
     def __init__(self,id):
        super().__init__(id)
        
       
x = TeachingAssistant('2675')
print(x.id)
y = Student('4567')
print(y.id)
z = Teacher('3421')
print(z.id)
p = Person('5749')
print(p.id)

2675TS
4567S
3421T
5749


In [8]:
n = int(input())
student_marks = {}
for _ in range(n):
    line = input().split()
    name, scores = line[0], line[1:]
    scores = map(float, scores)
    student_marks[name] = scores
query_name = input()
output = list(student_marks[query_name])    
per = sum(output)/len(output);
print("%.2f" % per); 

3
Krishna 67 68 69
Arjun 70 98 63
Malika 52 56 60
Malika
56.00


In [27]:
import numpy
numpy.set_printoptions(sign=' ')
a = numpy.array(input().split(),float)
print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [ ]:
import numpy

numpy.set_printoptions(sign=' ')

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.sum(my_array, axis = 0)         #Output : [4 6]
print numpy.sum(my_array, axis = 1)         #Output : [3 7]
print numpy.sum(my_array, axis = None)      #Output : 10
print numpy.sum(my_array)

In [28]:
import numpy

N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)], int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

2 2
1 2
3 4
24
